build:
  maxIssues: 10
  excludeCorrectable: false
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

config:
  validation: true
  warningsAsErrors: false
  excludes: "*/resources/*,*/build/*"

complexity:
  active: true
  ComplexInterface:
    active: false
  ComplexMethod:
    active: true
    threshold: 15
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  NestedBlockDepth:
    active: true
    threshold: 4

style:
  active: true
  ForbiddenComment:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
  MagicNumber:
    active: false
  WildcardImport:
    active: false